version: "3.8"

services:
  pgvector:
    image: agnohq/pgvector:16
    container_name: pgvector
    environment:
      POSTGRES_DB: ai-assistant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgvolume:/var/lib/postgresql/data
    ports:
      - "5532:5432"
    restart: always

volumes:
  pgvolume:
